# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "uas"
    "usbhid"
    "sd_mod"
    "r8169" # onboard lan
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "compress=zstd:5"
      "noatime"
      "space_cache=v2"
      "ssd"
      "subvol=root"
      "x-gvfs-trash"
    ];
  };

  boot.initrd.luks.devices."cryptroot".device =
    "/dev/disk/by-uuid/feb6878d-e53a-4b35-843e-dcdddc25ef6b";

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "compress=zstd:5"
      "noatime"
      "space_cache=v2"
      "ssd"
      "subvol=home"
      "x-gvfs-trash"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "compress=zstd:5"
      "noatime"
      "space_cache=v2"
      "ssd"
      "subvol=nix"
      "x-gvfs-trash"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0756-212F";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  zramSwap.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
