#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

FLAG="switch"

if [[ "$FLAG" != "switch" ]]; then
  echo -e "${RED}Supported flags: 'switch'${NC}"
  exit 1
fi

HOST=`scutil --get LocalHostName`
FLAKE_TARGET="darwinConfigurations.${HOST}.system"

export NIXPKGS_ALLOW_UNFREE=1

echo -e "${YELLOW}Starting build ($FLAG) for named host: $HOST${NC}"
nix --extra-experimental-features 'nix-command flakes' build .#$FLAKE_TARGET

if [[ "$FLAG" == "switch" ]]; then
  echo "${YELLOW}Switching to new generation...${NC}"
  sudo ./result/sw/bin/darwin-rebuild $FLAG --flake .#${HOST}
  echo -e "${GREEN}Switch to new generation complete!${NC}"
fi

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result
